=== uo295180/uo295180.github.io/xml/circuito.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns="http://www.uniovi.es" elementFormDefault="qualified" targetNamespace="http://www.uniovi.es" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="circuito">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre" />
				<xs:element ref="longitudcircuito" />
				<xs:element ref="anchura" />
				<xs:element ref="fecha" />
				<xs:element ref="hora" />
				<xs:element ref="vueltas" />
				<xs:element ref="localidad" />
				<xs:element ref="pais" />
				<xs:element ref="informacion" />
				<xs:element ref="multimedia" />
				<xs:element ref="salida" />
				<xs:element ref="tramos" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="nombre" type="xs:string" />
	<xs:element name="longitudcircuito">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:decimal">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="anchura">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:integer">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="fecha" type="xs:date" />
	<xs:element name="hora" type="xs:time" />
	<xs:element name="vueltas" type="xs:integer" />
	<xs:element name="localidad" type="xs:string" />
	<xs:element name="pais" type="xs:string" />
	<xs:element name="informacion">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="unbounded" ref="referencia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="referencia" type="xs:string" />
	<xs:element name="multimedia">
		<xs:complexType>
			<xs:choice>
				<xs:element minOccurs="1" maxOccurs="5" ref="fotografia" />
				<xs:element minOccurs="0" maxOccurs="3" ref="video" />
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="fotografia">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="url" />
				<xs:element minOccurs="0" maxOccurs="1" ref="pie" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="pie" type="xs:string" />
	<xs:element name="url" type="xs:string" />
	<xs:element name="video">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="url" />
				<xs:element minOccurs="0" maxOccurs="1" ref="pie" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="salida">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="coordenadas" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="coordenadas">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitud" />
				<xs:element ref="latitud" />
				<xs:element ref="altitud" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="longitud">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="gradosLongitud" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="latitud">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="gradosLatitud" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="altitud">
		<xs:simpleType>
			<xs:restriction base="xs:decimal">
				<xs:minInclusive value="0"/>
				<xs:maxInclusive value="8000"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="tramos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="tramo" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="tramo">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="distancia" />
				<xs:element ref="coordenadas" />
				<xs:element ref="sector" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="distancia">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:decimal">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="sector" type="xs:integer" />
	<xs:element name="gradosLatitud">
		<xs:simpleType>
			<xs:restriction base="xs:decimal">
				<xs:minInclusive value="-90"/>
				<xs:maxInclusive value="90"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>

	<xs:element name="gradosLongitud">
		<xs:simpleType>
			<xs:restriction base="xs:decimal">
				<xs:minInclusive value="0"/>
				<xs:maxInclusive value="180"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>

	
</xs:schema>

=== uo295180/uo295180.github.io/xml/circuitoEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>
<circuito xsi:schemaLocation="http://www.uniovi.es circuito.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.uniovi.es">
    <nombre>Shanghai International Circuit</nombre>
    <longitudcircuito unidades="metros">5451</longitudcircuito>
    <anchura unidades="metros">14</anchura>
    <fecha>2024-04-21</fecha>
    <hora>09:00:00</hora>
    <vueltas>56</vueltas>
    <localidad>Jiading, Shanghai</localidad>
    <pais>China</pais>
    <informacion>
        <referencia>https://en.wikipedia.org/wiki/Shanghai_International_Circuit</referencia>
        <referencia>https://www.formula1.com/en/results.html/2024/races/1011/china.html</referencia>
        <referencia>https://www.autosport.com/f1/news/shanghai-circuit-guide-2024-f1-chinese-gp/10414740/</referencia>
    </informacion>
    <multimedia>
        <fotografia>
            <url>CircuitoShangai.png</url>
            <pie>Fotografía del circuito de Shanghai</pie>
        </fotografia>
        <fotografia>
            <url>ImagenShangai.jpeg</url>
            <pie>Fotografía de dos coches en shangai</pie>
        </fotografia>
    </multimedia>
    <salida>
        <coordenadas>
            <longitud>
                <gradosLongitud>121.2202</gradosLongitud>
            </longitud>
            <latitud>
                <gradosLatitud>31.3372</gradosLatitud>
            </latitud>
            <altitud>4.11</altitud>
        </coordenadas>
    </salida>
    <tramos>
        <tramo>
            <distancia unidades="metros">0</distancia>
            <coordenadas>
                <longitud>
                    <gradosLongitud>121.2202</gradosLongitud>
                </longitud>
                <latitud>
                    <gradosLatitud>31.3372</gradosLatitud>
                </latitud>
                <altitud>4.11</altitud>
            </coordenadas>
            <sector>1</sector>
        </tramo>
        <tramo>
            <distancia unidades="metros">314</distancia>
            <coordenadas>
                <longitud>
                    <gradosLongitud>121.2172</gradosLongitud>
                </longitud>
                <latitud>
                    <gradosLatitud>31.3366</gradosLatitud>
                </latitud>
                <altitud>3.9</altitud>
            </coordenadas>
            <sector>1</sector>
        </tramo>
        <tramo>
            <distancia unidades="metros">83.37</distancia>
            <coordenadas>
                <longitud>
                    <gradosLongitud>121.2164</gradosLongitud>
                </longitud>
                <latitud>
                    <gradosLatitud>31.3369</gradosLatitud>
                </latitud>
                <altitud>3</altitud>
            </coordenadas>
            <sector>1</sector>
        </tramo>
        <tramo>
            <distancia unidades="metros">80</distancia>
            <coordenadas>
                <longitud>
                    <gradosLongitud>121.2161</gradosLongitud>
                </longitud>
                <latitud>
                    <gradosLatitud>31.3375</gradosLatitud>
                </latitud>
                <altitud>3</altitud>
            </coordenadas>
            <sector>1</sector>
        </tramo>
        <tramo>
            <distancia unidades="metros">61</distancia>
            <coordenadas>
                <longitud>
                    <gradosLongitud>121.2165</gradosLongitud>
                </longitud>
                <latitud>
                    <gradosLatitud>31.3380</gradosLatitud>
                </latitud>
                <altitud>4</altitud>
            </coordenadas>
            <sector>1</sector>
        </tramo>
        <tramo>
            <distancia unidades="metros">64.7</distancia>
            <coordenadas>
                <longitud>
                    <gradosLongitud>121.2172</gradosLongitud>
                </longitud>
                <latitud>
                    <gradosLatitud>31.3379</gradosLatitud>
                </latitud>
                <altitud>3</altitud>
            </coordenadas>
            <sector>1</sector>
        </tramo>
        <tramo>
            <distancia unidades="metros">68.7</distancia>
            <coordenadas>
                <longitud>
                    <gradosLongitud>121.2170</gradosLongitud>
                </longitud>
                <latitud>
                    <gradosLatitud>31.3372</gradosLatitud>
                </latitud>
                <altitud>2</altitud>
            </coordenadas>
            <sector>1</sector>
        </tramo>
        <tramo>
            <distancia unidades="metros">41.4</distancia>
            <coordenadas>
                <longitud>
                    <gradosLongitud>121.2174</gradosLongitud>
                </longitud>
                <latitud>
                    <gradosLatitud>31.3371</gradosLatitud>
                </latitud>
                <altitud>2</altitud>
            </coordenadas>
            <sector>1</sector>
        </tramo>
        <tramo>
            <distancia unidades="metros">83.56</distancia>
            <coordenadas>
                <longitud>
                    <gradosLongitud>121.2179</gradosLongitud>
                </longitud>
                <latitud>
                    <gradosLatitud>31.3377</gradosLatitud>
                </latitud>
                <altitud>2</altitud>
            </coordenadas>
            <sector>1</sector>
        </tramo>
        <tramo>
            <distancia unidades="metros">150.2</distancia>
            <coordenadas>
                <longitud>
                    <gradosLongitud>121.2169</gradosLongitud>
                </longitud>
                <latitud>
                    <gradosLatitud>31.3388</gradosLatitud>
                </latitud>
                <altitud>2</altitud>
            </coordenadas>
            <sector>1</sector>
        </tramo>
        <tramo>
            <distancia unidades="metros">166</distancia>
            <coordenadas>
                <longitud>
                    <gradosLongitud>121.2158</gradosLongitud>
                </longitud>
                <latitud>
                    <gradosLatitud>31.3399</gradosLatitud>
                </latitud>
                <altitud>4</altitud>
            </coordenadas>
            <sector>1</sector>
        </tramo>
        <tramo>
            <distancia unidades="metros">244.6</distancia>
            <coordenadas>
                <longitud>
                    <gradosLongitud>121.2149</gradosLongitud>
                </longitud>
                <latitud>
                    <gradosLatitud>31.3420</gradosLatitud>
                </latitud>
                <altitud>4</altitud>
            </coordenadas>
            <sector>2</sector>
        </tramo>
        <tramo>
            <distancia unidades="metros">21.09</distancia>
            <coordenadas>
                <longitud>
                    <gradosLongitud>121.2150</gradosLongitud>
                </longitud>
                <latitud>
                    <gradosLatitud>31.3422</gradosLatitud>
                </latitud>
                <altitud>4</altitud>
            </coordenadas>
            <sector>2</sector>
        </tramo>
        <tramo>
            <distancia unidades="metros">17.11</distancia>
            <coordenadas>
                <longitud>
                    <gradosLongitud>121.2152</gradosLongitud>
                </longitud>
                <latitud>
                    <gradosLatitud>31.3422</gradosLatitud>
                </latitud>
                <altitud>4</altitud>
            </coordenadas>
            <sector>2</sector>
        </tramo>
        <tramo>
            <distancia unidades="metros">99.43</distancia>
            <coordenadas>
                <longitud>
                    <gradosLongitud>121.2160</gradosLongitud>
                </longitud>
                <latitud>
                    <gradosLatitud>31.3416</gradosLatitud>
                </latitud>
                <altitud>4</altitud>
            </coordenadas>
            <sector>2</sector>
        </tramo>
        <tramo>
            <distancia unidades="metros">229.25</distancia>
            <coordenadas>
                <longitud>
                    <gradosLongitud>121.2172</gradosLongitud>
                </longitud>
                <latitud>
                    <gradosLatitud>31.3398</gradosLatitud>
                </latitud>
                <altitud>4</altitud>
            </coordenadas>
            <sector>2</sector>
        </tramo>
        <tramo>
            <distancia unidades="metros">58.34</distancia>
            <coordenadas>
                <longitud>
                    <gradosLongitud>121.2177</gradosLongitud>
                </longitud>
                <latitud>
                    <gradosLatitud>31.3395</gradosLatitud>
                </latitud>
                <altitud>4</altitud>
            </coordenadas>
            <sector>2</sector>
        </tramo>
        <tramo>
            <distancia unidades="metros">48.55</distancia>
            <coordenadas>
                <longitud>
                    <gradosLongitud>121.2182</gradosLongitud>
                </longitud>
                <latitud>
                    <gradosLatitud>31.3395</gradosLatitud>
                </latitud>
                <altitud>4</altitud>
            </coordenadas>
            <sector>2</sector>
        </tramo>
        <tramo>
            <distancia unidades="metros">87.38</distancia>
            <coordenadas>
                <longitud>
                    <gradosLongitud>121.2191</gradosLongitud>
                </longitud>
                <latitud>
                    <gradosLatitud>31.3397</gradosLatitud>
                </latitud>
                <altitud>2</altitud>
            </coordenadas>
            <sector>2</sector>
        </tramo>
        <tramo>
            <distancia unidades="metros">173.38</distancia>
            <coordenadas>
